### ISSUE TITLE
Initial install yields an unworkable setup on windows xp

### ISSUE THREAD

**Issue by Lawri-van-Buel** [dtd-tech/dtd-build#1]
Windows XP x32 yields an unworkable installation. due to!
- php is not 32-bits.
- when  path is used with spaces, UniController can not work with spaces in its paths. (at least in XP)

**Comment by SqyD** [comment]
- While I only have a 64-bit Windows 7 license to test with I just checked the .exe and dll files using independent tools (gnu "file" and "exe explorer" and can only find 32bit binaries. Can you elaborate what lead you to this conclusion? Did you have the same results with the stock UniserverZ distro at http://www.uniformserver.com/ ? Perhaps other limitations are at place.
- Space issue is a known limitation of the upstream package. Should indeed be part of the documentation.

**Comment by Lawri-van-Buel** [comment]
Testing in Windows XP 32 bits,   Version 11_8_1_ZeroXI.exe
- [x] Install into C:\web\
- [ ] Run Apache.
- [x] Run MySql.
- [ ] Run PHP.

**Comment by Lawri-van-Buel** [comment]
Issue Identified, A misguided errormessage and a missing dependency

To get it the base install to work when I did: 

> To run this version of UniServer the Visual C++ 2008 redistributable package is required.
> It can be downloaded from:
> MS Download Site Url:[http://goo.gl/I5NO5e](http://www.microsoft.com/downloads/en/details.aspx?FamilyID=A5C84275-3B97-4AB7-A40D-3802B2AF5FC2)

Result. we need to add this to the Download and perhaps auto install it so the program will work on all systems. most will have this due to other programs requireing it. bet we can not assume they do.

**Comment by Lawri-van-Buel** [comment]
I can get php and apache to work on XP when:
- [x] Install php 5.4
- [x] Disable the php_Curl module

however the webdites themselfves do not work

**Comment by SqyD** [comment]
As discussed we'll avoid pain and suffering by dropping XP as a supported platform for the Windows environment.
