### ISSUE TITLE
ISO image not working on 32-bits system when booting from USB stick with multiple partition on the main disc

### ISSUE THREAD

**Issue by Lawri-van-Buel** [dtd-tech/dtd-build#11]
It seems the installer makes some assumptions about the disc that are available. 

for example, on my system the /dev/sda holds a few partions (swap,Ubuntu,Arch,home) it claims /dev/sdb for the possibly mounted SD-card and any USB-drive gets /dev/sdc and further.

but the installer / starter of the image can not handle a disc not beeing present and fails with a loop of "failure to read /dev/sdb"

**Comment by SqyD** [comment]
Not sure how you build your bootable stick. I've tested it by installing a grub2 in the MBR of the usb drive. Just booting in a persistent live environment on that stick works fine on my machine with a drive with 7 partitions.

So, to be clear: you should NOT run the installer on actual hardware. We don't want students to accidently whipe their disks. I've even removed the install feature from the desktop.

**Comment by Lawri-van-Buel** [comment]
Steps to reproduce 
- have 2 disc in the system (hdd or alike)
- have the iso file copied to a usb stick using dd
- boot from the stick. (Option 1 is auto install, 2 is run live and 3 is manual install)
- choose any of the options. 

This result about halfwAy of the process in a infinity loop while searching for the install disc on /dev/sdb 

I suspect the install disc should be addressed through its UUID and not its variable mount location (the /dev/sd?)

**Comment by SqyD** [comment]
this is not a supported setup. closing
