### ISSUE TITLE
DTD Drupal8 uses hardcoded IP in its page.

### ISSUE THREAD

**Issue by Lawri-van-Buel** [dtd-tech/dtd-build#2]
When using a vm in which I installed the iso to a disk (a.k.a. a lubuntu install) I noticed that the Drupal8 front end requests its svg files from "http://192.168.178.31/core/misc/icons/bebebe/hamburger.svg" (which in our network is nowhere since were on a 10.10.0.0/24 network) 

![screenshot from 2015-09-18 11 52 59](https://cloud.githubusercontent.com/assets/4235191/9956814/dfc9fe3a-5dfb-11e5-8b72-e201e6ae2a3c.png)

**Comment by SqyD** [comment]
Good catch. I blame caching :-) Note that the dtd-main Drupal site lives at https://github.com/dtd-tech/dtd-main and will need a complete rebuild from scratch. For now it's just a placeholder.
