### ISSUE TITLE
image self awareness

### ISSUE THREAD

**Issue by florisvangeel** [dtd-tech/dtd-build#7]
Booted image in virtualbox without drive.
Seems to be working. it misses self awareness in hostname and /etc/hosts

Also site-name is labelled
![screen shot 2016-01-04 at 18 03 14](https://cloud.githubusercontent.com/assets/1267925/12095249/bb19504c-b30d-11e5-8b4c-ebf0951fc6f4.png)
 2015

**Comment by SqyD** [comment]
Not sure what you mean by "self aware". If it's knowing it's modified hostname from "lubuntu" (as it's "dtd-desktop" after install) that can be done with a few hacks I've found. Will probably need to address this as I'll be moving for the persistent boot from USB disk option.

**Comment by florisvangeel** [comment]
a default hostname i.e. "dtd-desktop.dtd" and /etc/hosts whete trackX.dtd are defined so the welcome landing page has working links to the training sites if your're running it in virtual machine or in USB boot mode.

**Comment by SqyD** [comment]
Will all be handled by the PAC file. Coming soon. See issue #6

**Comment by SqyD** [comment]
Pac file implemented. Done.
