### ISSUE TITLE
Strange shutdown operations?

### ISSUE THREAD

**Issue by florisvangeel** [dtd-tech/dtd-build#8]
ModemManager>?
Early crypto disks>?

System does not halt.
![screen shot 2016-01-04 at 18 11 51](https://cloud.githubusercontent.com/assets/1267925/12095421/c1f979b8-b30e-11e5-8395-c0d2a24d157c.png)

**Comment by SqyD** [comment]
Was this a shutdown of the live-cd or post install?

**Comment by florisvangeel** [comment]
live CD in virtualbox
